name: Release Go Module

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Verify Go module
        run: |
          echo "Verifying Go module..."
          go mod verify
          go mod tidy
          go mod download
          
          echo "Go module is ready for release"

      - name: Test Go module
        run: |
          echo "Running tests (main package only)..."
          go test .
          
          echo "All tests passed"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 